package com.lexcurious.ui;

import com.lexcurious.model.detail.ArticleUnit;
import com.lexcurious.model.detail.Clause;
import com.lexcurious.model.detail.Ho;
import com.lexcurious.model.detail.LawDetailWrapper;
import com.lexcurious.model.search.Law;
import com.lexcurious.model.tree.ArticleItem;
import com.lexcurious.model.tree.ClauseItem;
import com.lexcurious.model.tree.HoItem;
import com.lexcurious.ui.components.LawTreeCellRenderer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class LawDetailDialog extends JDialog {
    private JPanel contentPane;
    private JLabel lawNameLabel;
    private JTree lawTre;
    private JButton closeButton;

    public LawDetailDialog(Frame owner, Law law, LawDetailWrapper lawDetail) {
        super(owner, law.lawName() + " 상세 정보", true);
        $$$setupUI$$$();

        setContentPane(contentPane);
        setSize(600, 800);
        setLocationRelativeTo(owner);

        lawNameLabel.setText(law.lawName());
        lawTre.setModel(createLawTreeModel(law, lawDetail));
        lawTre.setCellRenderer(new LawTreeCellRenderer());

        closeButton.addActionListener(e -> dispose());
    }

    private DefaultTreeModel createLawTreeModel(Law law, LawDetailWrapper lawDetail) {
        if (lawDetail == null || lawDetail.lawDetails() == null) {
            return new DefaultTreeModel(new DefaultMutableTreeNode("상세 정보가 없습니다."));
        }

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(law.lawName());

        if (lawDetail.lawDetails().articlesWrapper() != null) {
            for (ArticleUnit article : lawDetail.lawDetails().articlesWrapper().articleUnits()) {
                List<ClauseItem> clauseItems = new ArrayList<>();
                ArticleItem articleItem = new ArticleItem(article.articleContent(), clauseItems);
                DefaultMutableTreeNode articleNode = new DefaultMutableTreeNode(articleItem);
                if (article.clause() != null) {
                    for (Clause clause : article.clause()) {
                        ClauseItem clauseItem = new ClauseItem(clause.clauseContent(), 0); // Clause does not have a like count
                        clauseItems.add(clauseItem);
                        DefaultMutableTreeNode clauseNode = new DefaultMutableTreeNode(clauseItem);

                        if (clause.ho() != null) {
                            for (Ho ho : clause.ho()) {
                                HoItem hoItem = new HoItem(ho);
                                clauseNode.add(new DefaultMutableTreeNode(hoItem));
                            }
                        }
                        articleNode.add(clauseNode);
                    }
                }
                root.add(articleNode);
            }
        }

        return new DefaultTreeModel(root);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(10, 10));
        lawNameLabel = new JLabel();
        Font lawNameLabelFont = this.$$$getFont$$$("Malgun Gothic", Font.BOLD, 20, lawNameLabel.getFont());
        if (lawNameLabelFont != null) lawNameLabel.setFont(lawNameLabelFont);
        lawNameLabel.setHorizontalAlignment(0);
        lawNameLabel.setText("Law Name");
        contentPane.add(lawNameLabel, BorderLayout.NORTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, BorderLayout.CENTER);
        lawTre = new JTree();
        scrollPane1.setViewportView(lawTre);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(panel1, BorderLayout.SOUTH);
        closeButton = new JButton();
        closeButton.setText("닫기");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}