package com.lexcurious.ui;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {
    public JPanel contentPane;
    private JButton button1;
    private JButton button2;
    private JButton button3;

    public MainFrame() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        setTitle("기묘한 법률 탐색기");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(contentPane);
        pack();
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        contentPane.setBackground(new Color(-1907998));
        contentPane.setEnabled(true);
        contentPane.setPreferredSize(new Dimension(350, 170));
        button1 = new JButton();
        button1.setText("Button");
        contentPane.add(button1);
        button2 = new JButton();
        button2.setText("Button");
        contentPane.add(button2);
        button3 = new JButton();
        button3.setText("Button");
        contentPane.add(button3);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
