package com.lexcurious.ui;

import com.lexcurious.api.LawApiClient;
import com.lexcurious.model.Law;
import com.lexcurious.ui.components.LawListCellRenderer;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {
    public JPanel contentPane;
    private JTextField searchTextField;
    private JButton searchButton;
    private JList<Law> resultList;
    private JScrollPane scrollPane;
    private JPanel searchPanel;
    private final LawApiClient lawApiClient;

    public MainFrame() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        setTitle("기묘한 법률 탐색기");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(contentPane);
        pack();
        setVisible(true);

        lawApiClient = new LawApiClient();
        resultList.setCellRenderer(new LawListCellRenderer());

        searchButton.addActionListener(e -> {
            // UI 확인을 위한 더미 데이터
            DefaultListModel<Law> listModel = new DefaultListModel<>();
            listModel.addElement(new Law(216946, "도로교통법", "도로교통법", 20240130, 19982, 20240731, "경찰청", "일부개정", "법률", "/DRF/lawService.do?OC=elpas&target=law&MST=216946&type=HTML&mobile=false"));
            listModel.addElement(new Law(216864, "공직선거법", "공선법", 20240123, 19958, 20240123, "중앙선거관리위원회", "일부개정", "법률", "/DRF/lawService.do?OC=elpas&target=law&MST=216864&type=HTML&mobile=false"));
            listModel.addElement(new Law(216854, "형법", "형법", 20240123, 19957, 20240724, "법무부", "일부개정", "법률", "/DRF/lawService.do?OC=elpas&target=law&MST=216854&type=HTML&mobile=false"));
            listModel.addElement(new Law(216146, "국가공무원법", "국가공무원법", 20231024, 19749, 20231024, "인사혁신처", "타법개정", "법률", "/DRF/lawService.do?OC=elpas&target=law&MST=216146&type=HTML&mobile=false"));
            resultList.setModel(listModel);
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setBackground(new Color(-1));
        contentPane.setPreferredSize(new Dimension(800, 600));
        searchPanel = new JPanel();
        searchPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        searchPanel.setBackground(new Color(-1));
        contentPane.add(searchPanel, BorderLayout.NORTH);
        searchTextField = new JTextField();
        searchTextField.setColumns(30);
        searchPanel.add(searchTextField);
        searchButton = new JButton();
        searchButton.setText("검색");
        searchPanel.add(searchButton);
        scrollPane = new JScrollPane();
        contentPane.add(scrollPane, BorderLayout.CENTER);
        resultList = new JList();
        scrollPane.setViewportView(resultList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}